document.getElementById('refreshButton').addEventListener('click', function() {
    var proverbs = [
        "Chase Atlantic - Falling",
        "Rihanna - Right Now",
        "Taylor Swift - Welcome To New York (Taylor's Version)",
        "Alan Walker, Sabrina Carpenter, Farruko - On My Way",
        "Ariana Grande - Gpd is a Woman",
        "Blackpink - Tally",
        "Madonna - La Isla Bonitta",
        "The Weeknd,  Post Malone - One Right Now",
        "Hande Yener - Havaalanı",
        "Gülşen - Saz mı Caz mı",
        "The Weeknd, Jennie, Lily-Rose Depp - One Of The Girls",
        "Manga - Bitti Rüya",
        "Beyonce, Shakira - Beautiful Liar",
        "Benny Blanco, Halsey, Khalid - Eastside",
        "Post Malone, Halsey, Future - Die For Me",
        "Tarkan - Dudu",
        "BTS - Spring Day",
        "The Weeknd, Madonna, Playboi Carti - Popular",
        "Dua Lipa - Love Again",
        "Edis - Arıyorum",
        "Melanie Martinez - Play Date",
        "Bella Porch - Build a Bitch",
        "Skylar Grey - Back From The Dead",
        "Cashmere Cat, Selena Gomez, Tory Lanez - Trust Nobody",
        "Katy Perry - Wide Awake",
        "Lady Gaga - Judas",
        "Dabid Guetta, Bebe Rexha - I'm Good (Blue) ",
        "William, Britney Spears - Scream & Shout",
        "Imagine Dragons - Bad Liar",
        "Doja Cat - Woman",
        "Loreen - Euphoria",
        "Nelly Furtado - Waiting For The Night",
        "Justin Bieber - Love Yourself",
        "Sean Paul - Temperature",
        "Black Eyed Peas - I Gotta Feeling",
        "Nicki Minaj - Super Bass",
        "Alicia Keys - Girl on Fire",
        "Jassie J - Domino",
        "Kesha - Die Young",
        "Jay-Z, Rihanna, Kanye West - Run This Town",
        "Ne-yo - Miss Independent",
        "Destiny's Child - Say My Name",
        "Nicki Minaj, Rihanna - Fly",
        "Camilla Cabello - Shameless",
        "PinkPantheress, Ice Spice - Boy's a Liar Pt.2",
        "Kenan Doğulu - Şans Meleğim",
        "Hepsi - Kalpsizsin",
        "Recep İvadik - Jenerik",
        "Magic System - Magic In The Air",
        "Ankaralı Namık - Ankara'nın Bağları",
        "Swedish House Mafia and The Weeknd - Moth To A Flame ",
        "Dua Lipa, İbrahim Tatlıses - Dom Dom Kurşunu & Blow Your Mind", 
        "coldplay - Fix You",
        "Artic Monkey - Arabella",
        "Maneskin - Gossip",
        "Lvbel C5 - Submariner",
        "Agust D - Haegum",
        "Taylor Swift - I Can Do It Wıth a Broken Heart",
        "Coldplay - Paradise",
        "Scorpions - No One Lıke You",
        "Shakira, Rihanna - Can't Remember To Forget You",
        "Adele - Lovin The Dark",
        "Bee Gees - Stayin' Alive",
        "Queen - I Was Born To Love You",
        "Scorpions - Love of My Life",
        "Frank Sinatra - That's Life",
        "Elvis Presley - Love Me Tender",
        "Maneskin - The Lonliest",
        "Doja Cat - Need to Know",
        "Sam Smith - Fire on Fire",
        "Lana Del Ray - Young & Beautiful",
        "Elvis Presley - Born in Love",
        "Guns N' Roses - Don't Cry",
        "Pink - Blow Me",
        "LP - Lost On You",
        "King of Lion - Sex on Fire",
        "Sia - Bird Set Free",
        "Coldplay - A Sky Full of Stars",
        "The Weeknd - Blinding Lights",
        "Pink Floyd - Wish You Were Here",
        "Ajda Pekkan - Kim Ne Derse Desin",
        "Adele - Don't You Remember",
        "Amy Winehouse - You Know I'm No Good",
        "Madison Beer - Reckless",
        "Amy Winehouse - Back to Black",
        "Otis Redding - Stand by Me",
        "Rihanna - Diamonds",
        "Rihanna - Stay",
        "Taylor Swift - 22 (Taylor's Version)",
        "Mliey Cyrus - Flowers",
        "Beyonce - Cuff It",
        "Katy Perry - Hot N Cold",
        "Justin Bieber - Favourite Girl",
        "Taylor Swift - Style (Taylor's Version)",
        "Shawn  Mendes - Treat You Better",
        "Beyonce - Halo",
        "Selena Gomez - Love You Like A Like Song",
        "Ali Atay - Bir Islıkta Sen Çal",
        "Ali Atay - Bıktık Vallahi",
        "ABBA - Dancing Queen",
        "Ekrem İmamoğlu - Tam Yol İleri",
        "Mansur Yavaş - Yavaş Ankara"
    ];
    var randomIndex = Math.floor(Math.random() * proverbs.length);
    document.getElementById('quote').textContent = proverbs[randomIndex];
});